PoDoDangJo/PDD

final-pjt-back/movies/urls.py, final-pjt-back/movies/views.py
인기순으로 영화 가져오는 기능 구현했습니다.
요청 url : http://127.0.0.1:8000/api/v1/movies/popularity/
사용 method : get
로그인여부 : X
=> [B006] Create Movie_popularity

final-pjt-front/src/components/TheModal/ReviewModal.vue, final-pjt-front/src/store/index.js
=> [F002] Update ReviewDelete

final-pjt-front/public/index.html, final-pjt-front/public/script.js, final-pjt-front/public/style.css, final-pjt-front/src/App.vue, final-pjt-front/src/components/StarRate.vue, final-pjt-front/src/components/TheModal/DetailModal/DetailComments.vue, final-pjt-front/src/components/TheModal/DetailModal/DetailModal.vue, final-pjt-front/src/components/TheModal/ReviewModal.vue, final-pjt-front/src/components/TheMovie/MovieList.vue, final-pjt-front/src/components/TheMovie/MovieListItem.vue, final-pjt-front/src/components/TheMovie/MovieSlider.vue, final-pjt-front/src/store/index.js
게시글 삭제 / 영화 상세정보 UI 개선 및 평가 / Home화면 animation
=> 내일 기본 구현 끝내기 목표입니다.

final-pjt-back/accounts/urls.py, final-pjt-back/accounts/views.py, final-pjt-back/movies/urls.py, final-pjt-back/movies/views.py
로그아웃 기능 구현하였습니다.
url : http://127.0.0.1:8000/accounts/delete/<username>/
method : POST
=> [B002] Create logout

final-pjt-back/movies/serializers.py, final-pjt-back/movies/urls.py, final-pjt-back/movies/views.py
감독 검색 기능 넣었습니다
actor와 같이 영화 id 넣으시면 됩니다.
method : GET
url : http://127.0.0.1:8000/api/v1/director/<영화아이디>/
=> [B006] Create movie_director

final-pjt-front/public/script.js, final-pjt-front/src/App.vue, final-pjt-front/src/components/StarRate.vue, final-pjt-front/src/components/TheHeader/SearchBar.vue, final-pjt-front/src/components/TheHeader/TheHeader.vue, final-pjt-front/src/components/TheModal/DetailModal/DetailComments.vue, final-pjt-front/src/components/TheModal/DetailModal/DetailInfo.vue, final-pjt-front/src/components/TheModal/DetailModal/DetailModal.vue, final-pjt-front/src/components/TheModal/DetailModal/DetailSimilar.vue, final-pjt-front/src/components/TheModal/SignUpModal.vue, final-pjt-front/src/components/TheMovie/MovieListItem.vue, final-pjt-front/src/components/TheMovie/MovieSlider.vue, final-pjt-front/src/store/index.js, final-pjt-front/src/views/CommunityView.vue, final-pjt-front/src/views/HomeView.vue, final-pjt-front/src/views/NotFound404View.vue
=> 댓글 게시글 프로필

final-pjt-back/movies/urls.py, final-pjt-back/movies/views.py, final-pjt-front/src/components/TheModal/CreateReviewModal.vue
=> [B006] movie_genre_&some_front

final-pjt-front/public/script.js, final-pjt-front/public/style.css, final-pjt-front/src/components/StarRate.vue, final-pjt-front/src/components/TheArticle/ArticleItem.vue, final-pjt-front/src/components/TheModal/DetailModal/DetailCommentItem.vue, final-pjt-front/src/components/TheModal/DetailModal/DetailComments.vue, final-pjt-front/src/components/TheModal/DetailModal/DetailModal.vue, final-pjt-front/src/store/index.js, final-pjt-front/src/views/HomeView.vue
=> [F002] Update Components

final-pjt-back/movies/serializers.py, final-pjt-back/movies/urls.py, final-pjt-back/movies/views.py
비슷한 영화 기능 구현하였습니다.
해당 영화 id와 영화 포스터 제공합니다.
login : X
method : GET
url : http://127.0.0.1:8000/api/v1/movies/similar/<영화 id>/
+ 이제 영화 디테일에서 배우 상세 내용이 포함됩니다.
+ 이제 첫 영화 평가에서 오류가 나지 않습니다!
=> [B006] Create movie_similar

final-pjt-back/movies/urls.py, final-pjt-back/movies/views.py
오늘 기준으로 15개 영상 데이터 주는 기능 입니다.
login : x
method : GET
url : http://127.0.0.1:8000/api/v1/movies/new/
http://127.0.0.1:8000/api/v1/movies/popular_actor/  - 인기 배우가 참여한 영화 [{배우 감독 정보}, {영화 정보}] # 3명의 배우분
http://127.0.0.1:8000/api/v1/movies/popular_director/ - 인기 감독이 만든 영화 [{영화 감독 정보}, {영화 정보}] # 3명의 감독분
+ 추가로 영화 검색 url 다른 양식과 마찬가지로 / 추가했습니다.
movies/search/<str:words_target>    ->    movies/search/<str:words_target>/
=> [B006] Create movie_new

final-pjt-front/src/App.vue, final-pjt-front/src/components/TheModal/DetailModal/DetailCommentItem.vue, final-pjt-front/src/components/TheModal/DetailModal/DetailComments.vue, final-pjt-front/src/components/TheModal/DetailModal/DetailInfo.vue, final-pjt-front/src/components/TheModal/DetailModal/DetailModal.vue, final-pjt-front/src/components/TheModal/DetailModal/DetailSimilar.vue, final-pjt-front/src/components/TheModal/ProfileModal.vue, final-pjt-front/src/store/index.js, final-pjt-front/src/views/CommunityView.vue, final-pjt-front/src/views/HomeView.vue
=> [F000] Update Components

final-pjt-front/src/store/index.js, final-pjt-front/src/views/HomeView.vue
=> [F001] Update HomeVue_GenreMovies

final-pjt-back/community/serializers.py, final-pjt-back/movies/serializers.py
user_id { username : 유저이름 } 이런식으로 추가하였습니다.
=> [B006] Update Review_comment&comment

final-pjt-front/src/App.vue, final-pjt-front/src/store/index.js, final-pjt-front/src/views/HomeView.vue
HomeVue 감독 배우 추천란 추가했습니다!
각각 인물 정보는 action단에서 묻어뒀습니다
=> [F001] Create HomeVue_dir&actor_m

final-pjt-back/accounts/serializers.py, final-pjt-back/community/views.py, final-pjt-back/movies/serializers.py, final-pjt-back/movies/views.py
=> [B006]Update logic

final-pjt-back/accounts/serializers.py, final-pjt-back/community/views.py, final-pjt-back/movies/serializers.py, final-pjt-back/movies/views.py, final-pjt-front/src/components/TheModal/ProfileAritcle.vue, final-pjt-front/src/components/TheModal/ProfileComment.vue, final-pjt-front/src/components/TheModal/ProfileLikeArticle.vue, final-pjt-front/src/components/TheModal/ProfileLikeRate.vue, final-pjt-front/src/components/TheModal/ProfileModal.vue, final-pjt-front/src/components/TheModal/ProfileRateMovie.vue, final-pjt-front/src/store/index.js
=> Profile view

final-pjt-back/accounts/views.py
=> [B002] Update accounts_delete

final-pjt-back/accounts/serializers.py
=> [B002] Update UserProfileSerializer

final-pjt-back/movies/views.py
=>  [B006] Update rate_delete

final-pjt-front/src/components/TheModal/ProfileAritcle.vue, final-pjt-front/src/components/TheModal/ProfileLikeRate.vue, final-pjt-front/src/components/TheModal/ProfileModal.vue
=> [F001] Update profileView
